#swagger 配置
swagger:
  title: 消息管理
  desc: 消息管理 API 操作文档
  version: 1.0
  termsOfServiceUrl: http://localhost:8080
  license: Apache 2.0
  licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
  basePackage: com.spring.api.swagger.controller
  groupName: 消息管理API
  contactName: niit
  contactUrl: https://github.com/zhayh/awesome-spring-boot.git
  contactEmail: zhayh@niit.edu.com
